---
global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entrypoints:
  web:
    address: :80
  websecure:
    address: :443  # HTTPS port
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
