---
# this file must go in /ect/netplan
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      addresses: [192.168.1.161/24]
      routes:
        - to: default
          via: 192.168.1.1
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
