---
networks:
  lev_network:
    external: true  # we will create the network externally
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: lev
    mac_address: ec:ca:08:19:09:27
    dns: [127.0.0.1, 1.1.1.1]
    ports: [443/tcp, 53/tcp, 53/udp, 67/udp, 80/tcp]  # expose all pihole ports.
    networks:
      lev_network:
        ipv4_address: 192.168.1.165  # IP of the pihole container 
    environment:
      FTLCONF_LOCAL_IPV4: 192.168.1.165  # must match with pihole.networks.pihole_network.ipv4_address
      TZ: America/NEW_YORK
      WEBPASSWORD_FILE: /run/secrets/pihole_password
      DNSSEC: 'true'
      PIHOLE_DOMAIN: pi.lan.lev
      DHCP_ACTIVE: 'true'
      DHCP_START: 192.168.1.2
      DHCP_END: 192.168.1.254
      DHCP_ROUTER: 192.168.1.1
    secrets: [pihole_password]
    volumes:
      - ~/homelab/etc-pihole:/etc/pihole
      - ~/home/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN  # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
secrets:
  pihole_password:
    environment: PIHOLE_PASSWORD  # environment variable
