---
version: '3.8'
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports: [9090:9090]
    command: [--config.file=/etc/prometheus/prometheus.yml]
    volumes: [./prometheus.yml:/etc/prometheus/prometheus.yml:ro]
    depends_on: [cadvisor]
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports: [8080:8080]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on: [pihole]
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host  # for DHCP server 
    environment:
      TZ: America/NEW_YORK
      WEBPASSWORD: PASSWORD
      # TODO: enable injection of the password via Docker Secrets 
      WEBPASSWORD_FILE: path_to_docker_secret
    volumes:
      - etc-pihole:/etc/pihole
      - etc-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN  # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
