---
networks:
  lev_network:
    external: true  # we will create the network externally
services:
  # TODO: now install wireguard and set it up
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    hostname: unbound
    networks:
      lev_network:
        ipv4_address: 192.168.1.69
    ports: [5335/tcp, 5335/udp]
    volumes: [./unbound/:/opt/unbound/etc/unbound/]  # custom unbound configuration
    environment:
      TZ: America/NEW_YORK
      ServerIP: 192.168.1.69
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: lev
    mac_address: ec:ca:08:19:09:27
    dns: [127.0.0.1, 1.1.1.1]
    ports: [443/tcp, 53/tcp, 53/udp, 67/udp, 80/tcp]  # expose all pihole ports.
    networks:
      lev_network:
        ipv4_address: 192.168.1.165  # IP of the pihole container 
    environment:
      FTLCONF_LOCAL_IPV4: 192.168.1.165  # must match with pihole.networks.pihole_network.ipv4_address
      TZ: America/NEW_YORK
      WEBPASSWORD_FILE: /run/secrets/pihole_password
      DNSSEC: 'true'
      PIHOLE_DOMAIN: pi.lan.lev
      DHCP_ACTIVE: 'true'
      DHCP_START: 192.168.1.2
      DHCP_END: 192.168.1.254
      DHCP_ROUTER: 192.168.1.1
      PIHOLE_DNS_: 192.168.1.69#5335 # must match unbound's ip address
    secrets: [pihole_password]
    depends_on: [unbound]
    volumes:
      - ~/homelab/etc-pihole:/etc/pihole
      - ~/homelab/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN  # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
secrets:
  pihole_password:
    environment: PIHOLE_PASSWORD  # environment variable
