---
services:
  traefik:
    image: traefik:v3.1.5
    container_name: traefik-reverse-proxy
    ports: [80:80, 8080:8080]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
    restart: unless-stopped
networks:
  lev_network:
    external: true
