---
networks:
  lev_network:
    external: true  # network was created manually
services:
  wireguard-easy:
    networks:
      lev_network:
        ipv4_address: 192.168.1.71
    container_name: wireguard-easy
    image: ghcr.io/wg-easy/wg-easy
    volumes: [~/wireguard-easy:/etc/wireguard]
    ports: [51820/udp, 51821/tcp]
    restart: unless-stopped
    cap_add: [NET_ADMIN, SYS_MODULE]
    sysctls: [net.ipv4.ip_forward=1, net.ipv4.conf.all.src_valid_mark=1]
    environment:
      PASSWORD_HASH: $$2a$$12$$eQmxub1MtDItGHUfnwt40eil0picMSWWqMetjGaUdlZ/8S9WvOLlK
      WG_PORT: 51820  # must match one of the specified ports above
      WG_DEFAULT_ADDRESS: 192.168.1.x
      WG_DEFAULT_DNS: 192.168.1.69#5335  # must match unbound's IP address 
      WG_ALLOWED_IPS: 192.168.1.0/24  # only allow in-network traffic
      WG_HOST: vpn.mylab.com
