---
secrets:
  cloudfare-token:
    file: ./cloudfare-token
networks:
  lev_network:
    external: true  # we will create the network externally
services:
  traefik:
    image: traefik:latest
    container_name: traefik-reverse-proxy
    ports:
      - 80:80  # HTTP port
      - 8080:8080  # Traefik entrypoint, is this needed?
      - 443:443  # HTTPS port
      - 10000:1000  # wireguard port 
    security_opt: [no-new-privileges:true]
    secrets: [cloudfare-token]
    env_file: [.env]
    environment:
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - CF_API_EMAIL=your@email.com
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cloudfare-token
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(`traefik-docker.technolev.work`)
      - traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}  # must be defined in .env file
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.traefik.middlewares=traefik-https-redirect
      - traefik.http.routers.traefik-secure.entrypoints=https
      - traefik.http.routers.traefik-secure.rule=Host(`traefik-docker.technolev.work`)
      - traefik.http.routers.traefik-secure.middlewares=traefik-auth
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=cloudflare
      - traefik.http.routers.traefik-secure.tls.domains[0].main=technolev.work
      - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.technolev.work
      - traefik.http.routers.traefik-secure.service=api@internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik-config/acme.json:/etc/traefik/acme.json
      - ./traefik-config/config.yaml:/etc/traefik/config.yaml:ro
    networks:
      lev_network:
        ipv4_address: 192.168.1.227
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    hostname: unbound
    networks:
      lev_network:
        ipv4_address: 192.168.1.226
    ports: [5335/tcp, 5335/udp]
    volumes: [./unbound-config/:/opt/unbound/etc/unbound/]  # custom unbound configuration
    environment:
      TZ: America/New_York
    restart: unless-stopped
  pihole:
    env_file: [.env]
    container_name: pihole
    image: pihole/pihole:2025.02.4
    hostname: pihole
    domainname: lev
    mac_address: ec:ca:08:19:09:27
    dns: [127.0.0.1, 1.1.1.1]
    ports:
      # DNS Ports
      - 53:53/tcp
      - 53:53/udp
      # Default HTTP Port
      - 80:80/tcp
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - 443:443/tcp
      # Uncomment the below if using Pi-hole as your DHCP Server
      - 67:67/udp
    networks:
      lev_network:
        ipv4_address: 192.168.1.225  # IP of the pihole container 
    environment:
      TZ: America/NEW_YORK
      FTLCONF_LOCAL_IPV4: 192.168.1.225  # must match with pihole.networks.pihole_network.ipv4_address
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_webserver_domain: technolev.lan
      FTLCONF_dns_upstreams: 192.168.1.226#5335
      FTLCONF_dns_dnssec: true
      FTLCONF_dhcp_active: true
      FTLCONF_dhcp_start: 192.168.1.6
      FTLCONF_dhcp_end: 192.168.1.224
      FTLCONF_dhcp_router: 192.168.1.1
      FTLCONF_dns_listeningMode: all
    depends_on: [unbound]
    volumes: [./etc-pihole:/etc/pihole]
    cap_add:
      - NET_ADMIN  # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
