---
name: deploy-traefik
on:
  push:
    paths: [traefik/**]
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: clean old checkout
        run: sudo chmod +w -R ${GITHUB_WORKSPACE}; sudo rm -rf ${GITHUB_WORKSPACE}/*;
      - uses: actions/checkout@v4
      - name: deploy traefik
        env:
          CLOUDFARE_API_TOKEN: ${{ secrets.CLOUDFARE_API_TOKEN }}
        run: cd ./traefik; docker compose down && docker compose up -d --remove-orphans
