---
name: deploy-rasp-pi
on:
  push:
    branches: [main]
    paths-ignore: [init-scripts/**, grafana/**, README.md]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: cleanup old checkout
        run: sudo chmod +w -R ${GITHUB_WORKSPACE}; sudo rm -rf ${GITHUB_WORKSPACE}/*;
      - uses: actions/checkout@v4

      - name: deploy pihole plus unbound
        env:
          PIHOLE_PASSWORD: ${{ secrets.PIHOLE_PASSWORD }}
        run: cd ./pi-hole; docker compose down && docker compose up -d --remove-orphans

      - name: deploy wireguard
        run: cd ./wireguard; docker compose down && docker compose up -d --remove-orphans

      - name: deploy traefik
        run: cd ./traefik; docker compose down && docker compose up -d --remove-orphans
