---
name: test
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: clean old checkout
        run: sudo chmod +w -R ${GITHUB_WORKSPACE}; sudo rm -rf ${GITHUB_WORKSPACE}/*;
      - uses: actions/checkout@v4
      - name: test
        run: ifconfig
      - name: ip route
        run: ip route
