---
name: test
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: clean old checkout
        run: sudo chmod +w -R ${GITHUB_WORKSPACE}; sudo rm -rf ${GITHUB_WORKSPACE}/*;
      - uses: actions/checkout@v4
      - name: test
        run: ifconfig
      - name: ip route
        run: ip route
      - name: test
        run: sudo systemctl status ssh
      - name: docker network
        run: "docker inspect $(docker network ls -q) | jq '.[] | {name: .Name, cidr:\
          \ .IPAM.Config[0].Subnet}'"
      - name: docker destroy
        run: docker compose down
      - name: remove network
        run: docker network rm lev_network
