---
# This is a basic workflow to help you get started with Actions
name: update-blocklists
# Controls when the workflow will run
on:
  schedule:
    - cron: 30 1 * * *
    # every day at 1:00 UTC
  workflow_dispatch:
jobs:
  update-blocklist:
    runs-on: self-hosted
    steps:
      - name: update pihole blocklist
        run: docker exec pihole pihole -g
